import type { Event } from '@/types/database'

// Real conference history, word-for-word from randolphrichards.com/conferences/
// ("Conferences (where I was the keynote speaker)"), used as a fallback when
// the `events` table in Supabase is empty. Without this, the page showed
// "Stay tuned, there are no events" -- which was wrong; the real site had a
// full keynote history, it just wasn't in the database yet.
export const STATIC_EVENTS: Event[] = [
  {
    id: 'mid-winter-bible-conference-2023',
    title: 'Reading the Jesus Story Frontwards',
    subtitle: '(rather than backwards, as we usually do) \u2014 six presentations',
    description: 'Keynote speaker, Mid-Winter Bible Conference.',
    event_date: '2023-03-01',
    event_time: '',
    end_date: null,
    venue: 'Mid-Winter Bible Conference',
    location: 'Hot Springs Village, AR',
    event_type: 'Keynote',
    register_url: '',
    image: '',
    status: 'past',
    created_at: '2023-03-01',
    updated_at: '2023-03-01',
  },
  {
    id: 'abide-conference-2023',
    title: 'Noticing What the Bible was Shouting at Us',
    subtitle: 'five presentations',
    description: 'Keynote speaker, Abide Conference.',
    event_date: '2023-02-01',
    event_time: '',
    end_date: null,
    venue: 'Abide Conference',
    location: 'Jonesboro, AR',
    event_type: 'Keynote',
    register_url: '',
    image: '',
    status: 'past',
    created_at: '2023-02-01',
    updated_at: '2023-02-01',
  },
  {
    id: 'network-biblical-storytellers-2023',
    title: 'Removing Cultural Blinders',
    subtitle: 'five presentations',
    description: 'Keynote speaker, Network of Biblical Storytellers.',
    event_date: '2023-02-15',
    event_time: '',
    end_date: null,
    venue: 'Network of Biblical Storytellers',
    location: 'Canada',
    event_type: 'Keynote',
    register_url: '',
    image: '',
    status: 'past',
    created_at: '2023-02-15',
    updated_at: '2023-02-15',
  },
  {
    id: 'ets-far-west-2022',
    title: 'Misreading Scripture',
    subtitle: 'two presentations',
    description: 'Evangelical Theological Society, Far West Region.',
    event_date: '2022-04-01',
    event_time: '',
    end_date: null,
    venue: 'Evangelical Theological Society, Far West Region',
    location: '',
    event_type: 'Presentation',
    register_url: '',
    image: '',
    status: 'past',
    created_at: '2022-04-01',
    updated_at: '2022-04-01',
  },
  {
    id: 'concordia-university',
    title: 'Society, Slant, and Scripture',
    subtitle: 'two presentations',
    description: 'Concordia University.',
    event_date: '2021-09-01',
    event_time: '',
    end_date: null,
    venue: 'Concordia University',
    location: '',
    event_type: 'Presentation',
    register_url: '',
    image: '',
    status: 'past',
    created_at: '2021-09-01',
    updated_at: '2021-09-01',
  },
]
